### ISSUE TITLE
Security review #2 issues

### ISSUE THREAD

**Issue by miohtama** [Firstbloodio/token#7]
- Multisig wallet and execute() - remove daily limit functionality. We want multisig to contract call execute() operations with zero value, as these can be operations like change founder.
- Left padding zeroes in web3 call conventions - https://github.com/ethereum/web3.js/issues/431 - 50% chance to fail deposit on crowdfunding page 
- Metamask and sale page UI needs polish - too confusing for end users

**Comment by JasonMcz** [comment]
> Left padding zeroes in web3 call conventions - ethereum/web3.js#431 - 50% chance to fail deposit on crowdfunding page.

Resolved by making a change on the front-end parsing the value.
